### ISSUE TITLE
When printing with only the right nozzle, the nozzle temperature from the second layer is set to 0

### ISSUE THREAD

**Issue by monohoshi** [macdylan/sm2uploader#15] opened 2024-02-25 08:02 UTC
Printed under general conditions with right nozzle only. 
When I set up as shown in the figure, the first layer prints correctly, but from the second layer the nozzle temperature is set to 0 and printing fails.
Also, changes in bed temperature were not recognized.
Temperatures on other layers do not seem to be reflected correctly.

![image](https://github.com/macdylan/sm2uploader/assets/137359537/96b19c58-eb31-4947-82b4-3e9d5cf7d880)

**Comment by macdylan** [comment] 2024-03-01 07:04
I can't reproduce it on J1, can you provide more information? it would be more helpful if you could provide gcode or 3mf file, thanks for your FDBK.

**Comment by macdylan** [comment] 2024-03-07 03:31
It seems that you are using the old profile, please try the latest profiles released in 2.7.1, there are some temperature controls for dual extruder.

<img width="712" alt="image" src="https://github.com/macdylan/sm2uploader/assets/331506/4f892b2c-2249-4438-9788-1dc2726f2d79">
<img width="666" alt="image" src="https://github.com/macdylan/sm2uploader/assets/331506/a5aa1148-487d-44a2-ba01-448438877b63">

**Closed** 2024-04-28 12:40 UTC
